services:
  nginx:
    image: nginx
    ports:
      - '8000:80'
    volumes:
      - './server:/var/www/html'
      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - mysql
      - reverb
  mysql:
    image: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: meep_db
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './server:/var/www/html'
    ports:
      - '9000:9000'
  composer:
    image: composer
    volumes:
      - './server:/var/www/html'
    working_dir: /var/www/html
  npm:
    image: node:alpine
    volumes:
      - './server:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm
  reverb:
    build:
      context: .
      dockerfile: reverb/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './server:/var/www/html'
    working_dir: /var/www/html
    depends_on:
      - mysql